name = "GameTracer"
uuid = "8cb375ce-8ac0-445a-ba91-c464b2953507"
authors = ["mnshkw <mao.nishikawa24@gmail.com> and contributors"]
version = "1.0.0-DEV"
license = "GPL-2.0-only"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
